// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-08DKgGAmg8lclMfUv9Y8osEB8leoxcQ',
    appId: '1:671002576425:web:5f5a29643b5429aca2fe38',
    messagingSenderId: '671002576425',
    projectId: 'e-box-4fbf2',
    authDomain: 'e-box-4fbf2.firebaseapp.com',
    storageBucket: 'e-box-4fbf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz8sH5SwmsDj3J-Mc5E72gkJFtv2_RQgY',
    appId: '1:671002576425:android:7a3354df63980e98a2fe38',
    messagingSenderId: '671002576425',
    projectId: 'e-box-4fbf2',
    storageBucket: 'e-box-4fbf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJyEiHBChyyjJbSu3fgDELmsC-MVWaIi0',
    appId: '1:671002576425:ios:4bff47edc0fdbdcea2fe38',
    messagingSenderId: '671002576425',
    projectId: 'e-box-4fbf2',
    storageBucket: 'e-box-4fbf2.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJyEiHBChyyjJbSu3fgDELmsC-MVWaIi0',
    appId: '1:671002576425:ios:4bff47edc0fdbdcea2fe38',
    messagingSenderId: '671002576425',
    projectId: 'e-box-4fbf2',
    storageBucket: 'e-box-4fbf2.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-08DKgGAmg8lclMfUv9Y8osEB8leoxcQ',
    appId: '1:671002576425:web:6913a3177711a037a2fe38',
    messagingSenderId: '671002576425',
    projectId: 'e-box-4fbf2',
    authDomain: 'e-box-4fbf2.firebaseapp.com',
    storageBucket: 'e-box-4fbf2.firebasestorage.app',
  );
}
